Improved deck summary component layout
Zero-to-Heroes/firestone pull request #112
Opened 2022-08-11 16:39 UTC by piedpiper358

Before:

![2022-08-11_19-13-44](https://user-images.githubusercontent.com/43519401/184183283-0a67e395-f50d-46d5-9936-85387590832c.png)

After:

![2022-08-11_19-03-20](https://user-images.githubusercontent.com/43519401/184179471-b45a578c-7cc1-4b21-99db-4510e111f69f.png)

I understand that it may not be very correct to use regular expressions to truncate the string, but it can't be done through toLocaleDateString.

2022-08-12 23:54 UTC, piedpiper358 commented
Do the same thing for mercs team summary.

![2022-08-13_02-44-04](https://user-images.githubusercontent.com/43519401/184457888-a84304dd-56d6-4c81-afdc-5e6ad06b422a.png)

2022-08-15 08:23 UTC, piedpiper358 commented
Don't like these changes? Btw, they concern not only the Russian language.

![2022-08-15_01-46-59](https://user-images.githubusercontent.com/43519401/184601158-dfecb30e-2ad0-4c66-9caa-faae6b564f54.png)

2022-08-15 08:48 UTC, sebastientromp commented
I added a comment in one of the files to better understand what is going on :)

And yeah, there are languages that take more room to say the same thing, but I'm not sure I want the app itself to handle all of the this (though accommodation can be made when it makes sense). I would rather that the translated strings themselves get shortened / abbreviated to fit inside the existing text.

2022-08-15 10:12 UTC, piedpiper358 commented
It seems to me that Firestone should stick to the general rule for localizable applications to leave about [30% extra space for other languages.](https://blog.alconost.com/en/how-to-prepare-a-game-for-localization) I think it can be done so that it doesn't look ugly in English.
For example, in this case, the lines in Russian are already shortened, but they still do not fit.

2022-08-19 07:53 UTC, sebastientromp commented
I wasn't aware of that rule, thanks.
However it might be quite a big endeavor for existing components. 
I have renamed the English string to read "Used: " instead of "Last used: ", which should make the text smaller.
For the first line in Italian, I think an alternate translation should be found, since "Tasso di vittoria" is twice as long as "Winrate"

2022-08-28 20:21 UTC, sebastientromp requested changes

2022-08-28 20:21 UTC, sebastientromp commented on core/src/js/components/decktracker/main/decktracker-deck-summary.component.ts
> +		.replace(/\s+г\./, ""); //truncate date in russian
So this removes the trailing r.? Could you explain what this stands for? There might be some built-in features to do that

2022-08-30 15:19 UTC, piedpiper358 commented on core/src/js/components/decktracker/main/decktracker-deck-summary.component.ts
> +		.replace(/\s+г\./, ""); //truncate date in russian
I googled it but the point is that toLocaleDateString function doesn't support anything like that. The year parameter can only be "numeric" - "2022 г." or "2-digit" - "22 г." Here is a page on [Stackoverflow](https://ru.stackoverflow.com/questions/816431/%D0%9A%D0%B0%D0%BA-%D1%83%D0%B1%D1%80%D0%B0%D1%82%D1%8C-%D0%93-%D0%B2-javsscript) with the same problem. We can instead make two calls to the toLocaleDateString function.

2022-09-05 18:48 UTC, sebastientromp commented
Not a big fan of the solution, but we can use this as a first step at least :)

2022-09-05 18:48 UTC, merged