Localize set names in set header and set component
Zero-to-Heroes/firestone pull request #136
Opened 2022-08-20 08:53 UTC by piedpiper358

**Before:**

![2022-08-20_11-48-30](https://user-images.githubusercontent.com/43519401/185737001-c19ec7a4-0317-4143-ab47-b44930b6b813.png)

![2022-08-20_11-48-11](https://user-images.githubusercontent.com/43519401/185737054-29957cdf-9567-4744-bb8a-2c3a027f262f.png)

**After:**

![2022-08-20_11-22-18](https://user-images.githubusercontent.com/43519401/185737019-d7c62c8d-581a-4306-8119-64e5a20787b9.png)

![2022-08-20_11-37-21](https://user-images.githubusercontent.com/43519401/185737059-4314d278-9b5e-41ee-ad76-103bcf0ea463.png)

2022-08-29 15:57 UTC, piedpiper358 commented
What's wrong with this?

2022-08-29 18:07 UTC, sebastientromp requested changes

2022-08-29 18:07 UTC, sebastientromp commented on core/src/js/components/collection/set.component.ts
> +						<span class="text set-name" *ngIf="_displayName" [owTranslate]=setName></span>
Could you add quotes around the `setName` prop?

2022-08-29 18:07 UTC, sebastientromp commented on core/src/js/components/main-window/global-header.component.ts
> +			<div class="text" [owTranslate]=text></div>
Same here

2022-08-29 18:07 UTC, sebastientromp commented
Sorry, forgot to end the review. You should be able to see my comments now

2022-09-05 14:20 UTC, merged

2022-09-14 20:08 UTC, piedpiper358 commented
After applying these changes, after clicking the back arrow in 'card-details' view (and going to 'cards' view), the state of global header isn't updated. I tried to understand why this is happening, but I couldn't figure it out.

**Before:**
![2022-09-14_22-53-38](https://user-images.githubusercontent.com/43519401/190251519-14434697-eb0a-4714-949a-c6fc189279dc.png)

**After:**
![2022-09-14_12-23-36](https://user-images.githubusercontent.com/43519401/190251577-59fe445e-63b4-45d6-b141-7b17bc2ab47b.png)