Improve layout of hero-power-info and signature-treasure-info
Zero-to-Heroes/firestone pull request #150
Opened 2022-08-21 22:40 UTC by piedpiper358

Add line break for "Win distribution" (for non-English languages). Align Winrate and Popularity labels to the right.  Remove duplicate properties.

**Before:**

![2022-08-21_19-02-21 2](https://user-images.githubusercontent.com/43519401/185812535-ed4ae874-04dc-4038-884f-88151c109630.png)

**After:**

![2022-08-22_01-29-33](https://user-images.githubusercontent.com/43519401/185813730-dbf3e7fb-f242-4569-896d-b464c3777dde.png)

2022-08-28 13:03 UTC, sebastientromp commented
The signature treasure has disappeared on the second screenshot, no?

2022-08-28 13:04 UTC, sebastientromp commented
I'm not too sure about aligning the labels to the right either. It's probably just a matter of taste, but I don't feel like it makes things easier to read or more pretty

2022-08-28 14:01 UTC, piedpiper358 commented
> The signature treasure has disappeared on the second screenshot, no?

No, this is my fault. The second screenshot shows the hero power selection window, so signature treasure shouldn't be displayed on it.

2022-08-28 20:19 UTC, sebastientromp requested changes

2022-08-28 20:19 UTC, sebastientromp commented on core/src/css/component/overlays/duels-ooc/duels-hero-power-info.component.scss
> +		text-align: right;
I would like to revert this change (as I said, I don't really think it looks clearer / better, and this kind of display is not used anywhere else in the app, so I don't think changing it right now is a good timing).

2022-08-28 20:19 UTC, sebastientromp commented on core/src/css/component/overlays/duels-ooc/duels-signature-treasure-info.component.scss
> +		text-align: right;
Same

2022-08-28 20:46 UTC, piedpiper358 commented on core/src/css/component/overlays/duels-ooc/duels-signature-treasure-info.component.scss
> +		text-align: right;
Ok

2022-08-28 21:07 UTC, piedpiper358 commented
What about centering the labels?

![2022-08-29_00-03-18](https://user-images.githubusercontent.com/43519401/187094519-6306a100-3a13-4365-9f4b-cda574b3c24c.png)

![2022-08-29_00-05-11](https://user-images.githubusercontent.com/43519401/187094518-c6928637-13f6-4785-b006-078945e6d045.png)

2022-08-29 06:15 UTC, sebastientromp commented
Why not, we can try this

2022-08-29 15:36 UTC, merged

2022-08-29 15:49 UTC, piedpiper358 commented
I also think that we need to add captions to the chart. Otherwise, it seems to be insufficiently informative.